services:
  - type: web
    name: ultra-powerful-openai
    runtime: docker
    env: python
    build:
      dockerfile: Dockerfile
    envVars:
      - key: API_KEY
        generateValue: true
      - key: REQUIRE_AUTH
        value: "true"
    plan: premium  # Pour une puissance 10x
    resources:
      cpu: 8
      memory: 16GB
    autoDeploy: true
